## Enra's and Cyrke's Sayonika definitions
## All the credits of Sayonika belong to sr229 "Enra" (Project Sayonika Designer) and Cyrke (Mascot design)
## These mascot's expressions and sprites are free for you to use in VN under Creative Commons 3.0 Non Commercial.
## Definitions file made by CPG Yuri

define sk = DynamicCharacter('sk_name', image='sk', what_prefix='"', what_suffix='"', ctc="ctc", ctc_position="fixed")
default sk_name = "Sayonika"

image sk 1 = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/a.png")
image sk 1a = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/a.png")
image sk 1b = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/b.png")
image sk 1c = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/c.png")
image sk 1d = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/d.png")
image sk 1e = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/e.png")
image sk 1f = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/f.png")
image sk 1g = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/g.png")
image sk 1h = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/h.png")
image sk 1i = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/i.png")
image sk 1j = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/j.png")
image sk 1k = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/k.png")
image sk 1l = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/l.png")
image sk 1l2 = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/l2.png")
image sk 1m = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/m.png")
image sk 1n = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/n.png")
image sk 1o = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/o.png")
image sk 1p = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/p.png")
image sk 1q = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/q.png")
image sk 1r = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/r.png")
image sk 1s = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/s.png")
image sk 1t = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/t.png")
image sk 1u = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/u.png")
image sk 1v = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/v.png")
image sk 1w = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/w.png")
image sk 1x = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/x.png")
image sk 1y = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/y.png")
image sk 1z = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/z.png")

image sk 2 = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/a.png")
image sk 2a = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/a.png")
image sk 2b = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/b.png")
image sk 2c = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/c.png")
image sk 2d = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/d.png")
image sk 2e = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/e.png")
image sk 2f = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/f.png")
image sk 2g = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/g.png")
image sk 2h = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/h.png")
image sk 2i = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/i.png")
image sk 2j = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/j.png")
image sk 2k = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/k.png")
image sk 2l = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/l.png")
image sk 2l2 = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/l2.png")
image sk 2m = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/m.png")
image sk 2n = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/n.png")
image sk 2o = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/o.png")
image sk 2p = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/p.png")
image sk 2q = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/q.png")
image sk 2r = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/r.png")
image sk 2s = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/s.png")
image sk 2t = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/t.png")
image sk 2u = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/u.png")
image sk 2v = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/v.png")
image sk 2w = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/w.png")
image sk 2x = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/x.png")
image sk 2y = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/y.png")
image sk 2z = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/z.png")

image sk 3 = Image("mod_assets/sayonika/3a.png")
image sk 3a = Image("mod_assets/sayonika/3a.png")
image sk 3b = Image("mod_assets/sayonika/3b.png")
image sk 3c = Image("mod_assets/sayonika/3c.png")
image sk 3d = Image("mod_assets/sayonika/3d.png")
image sk 3e = Image("mod_assets/sayonika/3e.png")
image sk 3f = Image("mod_assets/sayonika/3f.png")
image sk 3g = Image("mod_assets/sayonika/3g.png")
image sk 3h = Image("mod_assets/sayonika/3h.png")
image sk 3i = Image("mod_assets/sayonika/3i.png")
image sk 3j = Image("mod_assets/sayonika/3j.png")
image sk 3k = Image("mod_assets/sayonika/3k.png")
image sk 3l = Image("mod_assets/sayonika/3l.png")

image sk 4 = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/a.png")
image sk 4a = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/a.png")
image sk 4b = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/b.png")
image sk 4c = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/c.png")
image sk 4d = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/d.png")
image sk 4e = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/e.png")
image sk 4f = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/f.png")
image sk 4g = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/g.png")
image sk 4h = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/h.png")
image sk 4i = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/i.png")
image sk 4j = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/j.png")
image sk 4k = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/k.png")
image sk 4l = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/l.png")
image sk 4l2 = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/l2.png")
image sk 4m = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/m.png")
image sk 4n = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/n.png")
image sk 4o = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/o.png")
image sk 4p = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/p.png")
image sk 4q = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/q.png")
image sk 4r = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/r.png")
image sk 4s = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/s.png")
image sk 4t = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/t.png")
image sk 4u = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/u.png")
image sk 4v = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/v.png")
image sk 4w = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/w.png")
image sk 4x = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/x.png")
image sk 4y = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/y.png")
image sk 4z = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/z.png")
